<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MovieSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('movies')->insert([
            [
                'movie_id' => 1,
                'title' => 'Tử Chiến Trên Không',
                'slug' => 'tu-chien-tren-khong-1',
                'cate_id' => 1,
                'director' => 'Lê Nhật Quang',
                'duration' => 118,
                'description' => 'Tử Chiến Trên Không kể về Bình, chuyên viên cảnh vệ hàng không...',
                'release_date' => '2025-09-19',
                'early_premiere_date' => null,
                'poster' => 'tu-chien-tren-khong.jpg',
                'trailer' => 'https://www.youtube.com/watch?v=iJ6lKh698Js',
                'rating' => 43,
                'age_limit' => 16,
                'status' => 3,
                'created_at' => '2025-08-15',
            ],
            [
                'movie_id' => 2,
                'title' => 'Cậu Bé Cá Heo và Bí Mật 7 Đại Dương',
                'slug' => 'cau-be-ca-heo-va-bi-mat-7-dai-duong-2',
                'cate_id' => 5,
                'director' => 'Mohammad Kheirandish',
                'duration' => 96,
                'description' => 'Cậu bé cá heo và những người bạn đồng hành...',
                'release_date' => '2025-10-03',
                'early_premiere_date' => null,
                'poster' => 'cau-be-ca-heo-va-bi-mat-7-dai-duong.png',
                'trailer' => 'https://www.youtube.com/watch?v=EqK34MmMqrE',
                'rating' => 40,
                'age_limit' => 0,
                'status' => 3,
                'created_at' => '2025-09-03',
            ],
            [
                'movie_id' => 3,
                'title' => 'Bịt Mắt Bắt Nai',
                'slug' => 'bit-mat-bat-nai-3',
                'cate_id' => 4,
                'director' => 'Hoàng Thơ',
                'duration' => 92,
                'description' => 'Trang - một nhân viên bất động sản...',
                'release_date' => '2025-10-31',
                'early_premiere_date' => null,
                'poster' => 'bit-mat-bat-nai.png',
                'trailer' => 'https://www.youtube.com/watch?v=ABdyHbWAPIQ',
                'rating' => 45,
                'age_limit' => 16,
                'status' => 2,
                'created_at' => '2025-10-01',
            ],
            [
                'movie_id' => 4,
                'title' => 'Cục Vàng Của Ngoại',
                'slug' => 'cuc-vang-cua-ngoai-4',
                'cate_id' => 2,
                'director' => 'Khương Ngọc',
                'duration' => 119,
                'description' => 'Lấy cảm hứng từ những ký ức tuổi thơ...',
                'release_date' => '2025-10-17',
                'early_premiere_date' => null,
                'poster' => 'cuc-vang-cua-ngoai.jpg',
                'trailer' => 'https://www.youtube.com/watch?v=Yy2QGcImoKI&t=1s',
                'rating' => 46,
                'age_limit' => 13,
                'status' => 2,
                'created_at' => '2025-10-01',
            ],
            [
                'movie_id' => 5,
                'title' => 'Cải Mả',
                'slug' => 'cai-ma-5',
                'cate_id' => 4,
                'director' => 'Thắng Vũ',
                'duration' => 115,
                'description' => 'Khi đại gia đình ông Quang trở về quê...',
                'release_date' => '2025-10-31',
                'early_premiere_date' => null,
                'poster' => 'cai-ma.png',
                'trailer' => 'https://www.youtube.com/watch?v=b_0KRi-6xRg',
                'rating' => 45,
                'age_limit' => 16,
                'status' => 2,
                'created_at' => '2025-10-01',
            ],
            [
                'movie_id' => 6,
                'title' => 'Phá Đám Sinh Nhật Mẹ',
                'slug' => 'pha-dam-sinh-nhat-me-6',
                'cate_id' => 2,
                'director' => 'Nguyễn Thanh Bình',
                'duration' => 91,
                'description' => 'Bị giang hồ đe doạ...',
                'release_date' => '2025-10-30',
                'early_premiere_date' => null,
                'poster' => 'pha-dam-sinh-nhat-me.jpg',
                'trailer' => 'https://www.youtube.com/watch?v=dBsJYwaBbLA&t=2s',
                'rating' => 40,
                'age_limit' => 16,
                'status' => 2,
                'created_at' => '2025-10-01',
            ],
            [
                'movie_id' => 7,
                'title' => 'Tình Người Duyên Ma 2025',
                'slug' => 'tinh-nguoi-duyen-ma-2025-7',
                'cate_id' => 3,
                'director' => 'Choosak Iamsook',
                'duration' => 104,
                'description' => 'Lấy cảm hứng từ truyền thuyết Mae Nak...',
                'release_date' => '2025-11-07',
                'early_premiere_date' => null,
                'poster' => 'tinh-nguoi-duyen-ma-2025.png',
                'trailer' => 'https://www.youtube.com/watch?v=xUhwAp08Q08',
                'rating' => 39,
                'age_limit' => 13,
                'status' => 2,
                'created_at' => '2025-10-01',
            ],
            [
                'movie_id' => 8,
                'title' => 'Quỷ Tha Ma Bắt: Thai Chiêu Tài',
                'slug' => 'quy-tha-ma-bat-thai-chieu-tai-8',
                'cate_id' => 4,
                'director' => 'Trần Nhân Kiên',
                'duration' => 104,
                'description' => 'Nhơn, một doanh nhân thành đạt...',
                'release_date' => '2025-11-07',
                'early_premiere_date' => null,
                'poster' => 'thai-chieu-tai.jpg',
                'trailer' => 'https://www.youtube.com/watch?v=2kANaFSWCgQ',
                'rating' => 46,
                'age_limit' => 18,
                'status' => 2,
                'created_at' => '2025-10-15',
            ],
            [
                'movie_id' => 9,
                'title' => 'Truy Tìm Long Diên Hương',
                'slug' => 'truy-tim-long-dien-huong-9',
                'cate_id' => 3,
                'director' => 'Dương Minh Chiến',
                'duration' => 103,
                'description' => 'Báu vật làng biển Long Diên Hương...',
                'release_date' => '2025-11-14',
                'early_premiere_date' => null,
                'poster' => 'truy-tim-long-dien-huong.jpg',
                'trailer' => 'https://www.youtube.com/watch?v=aTVcY0QlWAE&t=2s',
                'rating' => 44,
                'age_limit' => 16,
                'status' => 2,
                'created_at' => '2025-10-15',
            ],
            [
                'movie_id' => 10,
                'title' => 'Mộ Đom Đóm',
                'slug' => 'mo-dom-dom-10',
                'cate_id' => 5,
                'director' => 'Isao Takahata',
                'duration' => 89,
                'description' => 'Câu chuyện cảm động về tình anh em...',
                'release_date' => '2025-11-07',
                'early_premiere_date' => null,
                'poster' => 'mo-dom-dom.png',
                'trailer' => null,
                'rating' => 41,
                'age_limit' => 0,
                'status' => 3,
                'created_at' => '2025-10-15',
            ],
            [
                'movie_id' => 11,
                'title' => 'Trái Tìm Què Quặt',
                'slug' => 'trai-tim-que-quat-11',
                'cate_id' => 1,
                'director' => 'Nguyễn Quốc Công',
                'duration' => 102,
                'description' => 'Một vụ án máu chấn động thị trấn...',
                'release_date' => '2025-11-07',
                'early_premiere_date' => null,
                'poster' => 'trai-tim-que-quat.jpg',
                'trailer' => 'https://www.youtube.com/watch?v=vAZnD-kG68g&t=1s',
                'rating' => 42,
                'age_limit' => 18,
                'status' => 2,
                'created_at' => '2025-10-15',
            ],
            [
                'movie_id' => 12,
                'title' => 'Quán Kỳ Nam',
                'slug' => 'quan-ky-nam-12',
                'cate_id' => 2,
                'director' => 'Lê Nhật Quang (Leon Le)',
                'duration' => 120,
                'description' => 'Câu chuyện đầy chiều sâu trong khu chung cư...',
                'release_date' => '2025-11-28',
                'early_premiere_date' => null,
                'poster' => 'quan-ky-nam.jpg',
                'trailer' => 'https://www.youtube.com/watch?v=0X0C-9nSNwQ',
                'rating' => null,
                'age_limit' => 16,
                'status' => 2,
                'created_at' => '2025-10-15',
            ],
            [
                'movie_id' => 13,
                'title' => 'Bẫy Tiền',
                'slug' => 'bay-tien-13',
                'cate_id' => 1,
                'director' => 'Oscar Dương',
                'duration' => 120,
                'description' => 'Một vụ lừa đảo qua điện thoại...',
                'release_date' => '2025-11-22',
                'early_premiere_date' => null,
                'poster' => 'bay-tien.jpg',
                'trailer' => 'https://www.youtube.com/watch?v=hmcD4eg8Do8',
                'rating' => 40,
                'age_limit' => 13,
                'status' => 2,
                'created_at' => '2025-11-01',
            ],
            [
                'movie_id' => 14,
                'title' => 'Cưới vợ cho cha',
                'slug' => 'cuoi-vo-cho-cha-14',
                'cate_id' => 2,
                'director' => 'Nguyễn Ngọc Lâm',
                'duration' => 112,
                'description' => 'Một câu chuyện gia đình miền Tây...',
                'release_date' => '2025-11-21',
                'early_premiere_date' => null,
                'poster' => 'cuoi-vo-cho-cha.png',
                'trailer' => 'https://www.youtube.com/watch?v=pXCRj4OMLg0',
                'rating' => 41,
                'age_limit' => 0,
                'status' => 2,
                'created_at' => '2025-11-01',
            ],
            [
                'movie_id' => 15,
                'title' => 'Wicked: Phần 2',
                'slug' => 'wicked-phan-2-15',
                'cate_id' => 5,
                'director' => 'Jon M. Chu',
                'duration' => 138,
                'description' => 'Chương cuối của câu chuyện Elphaba...',
                'release_date' => '2025-11-21',
                'early_premiere_date' => null,
                'poster' => 'wicked_2.png',
                'trailer' => null,
                'rating' => 42,
                'age_limit' => 0,
                'status' => 2,
                'created_at' => '2025-11-01',
            ],
            [
                'movie_id' => 16,
                'title' => 'Thế Hệ Kỳ Tích (Bà Đừng Buồn Con)',
                'slug' => 'the-he-ky-tich-ba-dung-buon-con-16',
                'cate_id' => 2,
                'director' => 'Hoàng Nam',
                'duration' => 120,
                'description' => 'Chàng sinh viên Tiến và giấc mơ...',
                'release_date' => '2025-12-12',
                'early_premiere_date' => null,
                'poster' => 'the-he-ky-tich.png',
                'trailer' => null,
                'rating' => null,
                'age_limit' => 13,
                'status' => 1,
                'created_at' => '2025-11-01',
            ],
            [
                'movie_id' => 17,
                'title' => 'Ai Thương Ai Mến',
                'slug' => 'ai-thuong-ai-men-17',
                'cate_id' => 2,
                'director' => 'Thu Trang',
                'duration' => 120,
                'description' => 'Bộ phim lấy bối cảnh miền Tây...',
                'release_date' => '2026-01-01',
                'early_premiere_date' => null,
                'poster' => 'ai-thuong-ai-men.jpg',
                'trailer' => null,
                'rating' => null,
                'age_limit' => 13,
                'status' => 1,
                'created_at' => '2025-11-01',
            ],
            [
                'movie_id' => 18,
                'title' => 'Hoàng Tử Quỷ',
                'slug' => 'hoang-tu-quy-18',
                'cate_id' => 4,
                'director' => 'Trần Hữu Tấn',
                'duration' => 120,
                'description' => 'Hoàng tử được sinh ra nhờ tà thuật...',
                'release_date' => '2025-12-05',
                'early_premiere_date' => null,
                'poster' => 'hoang-tu-quy.png',
                'trailer' => 'https://www.youtube.com/watch?v=8sN-kdDxPSM',
                'rating' => null,
                'age_limit' => 16,
                'status' => 2,
                'created_at' => '2025-11-01',
            ],
        ]);
    }
}
